// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7-ZG6pX06geA7VQJQ8atYbYf1jp7J1lU',
    appId: '1:479057193984:web:8e0e7685bcc0c3dcc17ce5',
    messagingSenderId: '479057193984',
    projectId: 'rent-everything-5b7e7',
    authDomain: 'rent-everything-5b7e7.firebaseapp.com',
    storageBucket: 'rent-everything-5b7e7.firebasestorage.app',
    measurementId: 'G-P3HSC4S6GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ADpGrR1fIzYlVnVTGhLYWWoqLPqwpPc',
    appId: '1:479057193984:android:e8cea338c0175827c17ce5',
    messagingSenderId: '479057193984',
    projectId: 'rent-everything-5b7e7',
    storageBucket: 'rent-everything-5b7e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ppPMUsPpEBk_gLyAO6spYUddmS7odlo',
    appId: '1:479057193984:ios:0ed1b6d9e15fdccec17ce5',
    messagingSenderId: '479057193984',
    projectId: 'rent-everything-5b7e7',
    storageBucket: 'rent-everything-5b7e7.firebasestorage.app',
    iosBundleId: 'com.example.rentEverything',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7-ZG6pX06geA7VQJQ8atYbYf1jp7J1lU',
    appId: '1:479057193984:web:cb9a19f2b7cbb0a2c17ce5',
    messagingSenderId: '479057193984',
    projectId: 'rent-everything-5b7e7',
    authDomain: 'rent-everything-5b7e7.firebaseapp.com',
    storageBucket: 'rent-everything-5b7e7.firebasestorage.app',
    measurementId: 'G-B5P2ZCN9E1',
  );
}
